### ISSUE TITLE
Bug Fix: PML

### ISSUE THREAD

**Issue by hammy4815** [BYUCamachoLab/emepy#18]
Currently the PML implementation is unfinished and buggy. Default EMpy boundary conditions are being used. Only Lumerical API has a working PML boundary condition at the moment. Possibly, this could be addressed in conjunction with the modified mode solver.

**Comment by hammy4815** [comment]
Maybe we want to change how boundary conditions are dealt with in EMEPy completely. Currently it's a very ugly flag that gets passed in as a boolean.

**Comment by 694856790** [comment]
Looking forward to your fix for PML, will it be possible to support mode solving for Bend when PML is available?

**Comment by hammy4815** [comment]
Hi @694856790,

I have mostly implemented PML using the tidy3d modesolver which can be found on the tidy3d branch. Eventually this will be merged with main. Their mode solver also allows for bend radii when solving. In the future, we will likely provide eme support for bends as well in emepy using this mode solver routine. Thanks!

**Comment by 694856790** [comment]
Hi, thank you for your reply! I have been studying your masterpiece recently. I understand that the accuracy of the EME algorithm results is related to all the modes solved (such as EME of Lumerical MODE), but the modes solved by FDE in EMEpy are quite different from those of Lumerical and COMSOL in high-order modes (after comparison, the results of Lumerical and COMSOL are quite consistent), I would like to ask you if EMEpy can modify some parameters to make it consistent with the simulation results of commercial software. Is there a problem with the metal boundary conditions? Thanks!

> Hi @694856790,
> 
> I have mostly implemented PML using the tidy3d modesolver which can be found on the tidy3d branch. Eventually this will be merged with main. Their mode solver also allows for bend radii when solving. In the future, we will likely provide eme support for bends as well in emepy using this mode solver routine. Thanks!

**Comment by 694856790** [comment]
> Hi @694856790,
> 
> Thank you for your feedback. I have a few suggestions and questions to help debug the differences you experience.
> 
> First, Lumerical has a fancy sub pixel smoothing method that creates more accurate mode solves at a given resolution. We also have our own sub pixel smoothing but it only works if you provide the polygon (waveguide width and thickness if you are just calling a mode solver). If you are providing a raw permittivity profile, then it will not use sub pixel smoothing and will be less accurate unless you have a very fine resolution.
> 
> The quickest way to test the differences is to extract the permittivity profile provided by Lumerical and feed it into our mode solver. At the moment, EMEPy only uses a simply profile where the permittivity is the same in every vectorized direction, but electromagnetic python does allow for a permittivity tensor. My first guess is that because Lumerical is using a tensor where the sub pixel smoothing is dependent on the directionality of epsilon, those small differences on the edges of the waveguide are noticeable for higher order modes. So if feeding in one of the directions from Lumerical to EMEPy does not benchmark results successfully, we will need to allow for the full tensor to be fed in.
> 
> If the issue is not related to sub pixel smoothing and the tensor profile, I have some other ideas.
> 
> Since EMEPy is using Electromagnetic python and tidy3d wrappers to perform mode-solving, the accuracy will be entirely dependent on those parameters we pass to their solvers (which I think is what you were saying). With the higher order modes, it can be tricky sometimes. Lumerical seems to have in place an efficient algorithm for excluding the spurious modes that are solved for in their backend, and organizes the physical modes by TE and TM as well.
> 
> Using electromagnetic python, all modes (including spurious) that are solved for are returned simply in the order of their effective index. We have in place a simple way to exclude spurious modes using an estimated threshold for the ratio of power in the core vs the cladding, which can be adjusted. The polarization, however, as I mentioned is just provided in the order of their effective index.
> 
> So the first thing to check is to ensure that the same mode order and polarization is being compared between various solvers. If you're sure that the same polarization and mode index is compared between our wrappers and Lumerical, there are a few other ideas that come to mind. Are you using PML with Lumerical and COMSOL? If so, the tidy3d wrapper we now have is better to use as it allows for PML boundaries.
> 
> However, if you're using a standard silicon core around 1.5µm surrounded by a full oxide cladding, with enough cladding the results seem to be quite similar with and without PML since the fields are fairly confined (near fundamental mode orders at least). I haven't explored wavelengths outside of the 1.4-1.6 µm region with these mode solvers and generally don't go beyond 10 orders of modes, so if you're doing that then the spurious threshold might need to be adjusted as well as the mesh density. Possibly some other parameters as well.
> 
> In addition, are you using the same mesh grid for EMEPy as with Lumerical? I know Lumerical does some sneaky tricks sometimes to estimate finer grids than are provided so sometimes a denser grid is needed in EMEPy. But the only major tricks for Lumerical MODE I'm aware of are 1) sub pixel smoothing and 2) some sort of analytical-computational hybrid approach to estimating transmissions across a wavelength band.
> 
> Otherwise if none of these ideas seem to fix the discrepancies than we might need to take a deeper dive into the boundary conditions used by electromagnetic python ( which I assume is the wrapper you are using).
> 
> Let me know if you want some clarification on any of these points or if you have any disagreements and I would be happy to discuss further.
> 
> Thanks, Ian

Hi, thank you for taking the time to reply me, I have tested some of your suggestions before. I have some resonance with some of your ideas. Lumerical's sub-pixel smoothing does exist. When I observed the index distribution on the monitor, I found that the index at the edge of the object was between the refractive index of the cladding and the core layer. Lumerical's sub-pixel smoothing operation may be performed using the “Sigmoid” function. Smoothing, not quite the same as EMEpy (I found that EMEpy's sub-pixel smoothing results in a smaller Neff than Lumerical), I guess the sub-pixel smoothing method is the source of the smaller difference in the fundamental modes. But for higher-order modes, I don't think sub-pixel smoothing is the main reason, because I found in testing that changes in the thickness of the boundary layer (the n_layer parameter) cause significant changes in the Neff for higher-order modes (you can test it), but I didn't find the most correct parameters. In addition, during the test comparison between EMEpy and Lumerical, I used the same boundary conditions (Metal or PEC? I may not have described it very professionally) and the same mesh structure, and I also tested rectangular silicon waveguides at a wavelength of 1.55 microns, the refractive index of the core layer is 3.47, the thickness is 0.22 microns, and the width is 0.40 microns; the refractive index of the cladding layer is 1.444, and the thickness and width are both 3 microns. Although I don't know what kind of tricks Lumerical used, it's really amazing that they can achieve the same results as those calculated by a FEM algorithm like Comsol. I hope that our discussions can improve the accuracy and reliability of numerical calculation of EMEpy. Finally, I noticed that you mentioned Tidy3d for mode solving. As far as I know, the project is closed source. Excuse me, how did you do it?

**Comment by 694856790** [comment]
@hammy4815 Hi, thank you for taking the time to reply me, I have tested some of your suggestions before. I have some resonance with some of your ideas. Lumerical's sub-pixel smoothing does exist. When I observed the index distribution on the monitor, I found that the index at the edge of the object was between the refractive index of the cladding and the core layer. Lumerical's sub-pixel smoothing operation may be performed using the “Sigmoid” function. Smoothing, not quite the same as EMEpy (I found that EMEpy's sub-pixel smoothing results in a smaller Neff than Lumerical), I guess the sub-pixel smoothing method is the source of the smaller difference in the fundamental modes. But for higher-order modes, I don't think sub-pixel smoothing is the main reason, because I found in testing that changes in the thickness of the boundary layer (the n_layer parameter) cause significant changes in the Neff for higher-order modes (you can test it), but I didn't find the most correct parameters. In addition, during the test comparison between EMEpy and Lumerical, I used the same boundary conditions (Metal or PEC? I may not have described it very professionally) and the same mesh structure, and I also tested rectangular silicon waveguides at a wavelength of 1.55 microns, the refractive index of the core layer is 3.47, the thickness is 0.22 microns, and the width is 0.40 microns; the refractive index of the cladding layer is 1.444, and the thickness and width are both 3 microns. Although I don't know what kind of tricks Lumerical used, it's really amazing that they can achieve the same results as those calculated by a FEM algorithm like Comsol. I hope that our discussions can improve the accuracy and reliability of numerical calculation of EMEpy. Finally, I noticed that you mentioned Tidy3d for mode solving. As far as I know, the project is closed source. Excuse me, how did you do it?

**Comment by hammy4815** [comment]
@694856790 ,

Thanks for the reply. I'll first address your question regarding our tidy3d wrapper - Indeed you are correct that the tidy3d FDTD engine is closed source and requires a pay-per simulation routine. However, they have open sourced their mode-solver. [Here is there example](https://docs.flexcompute.com/projects/tidy3d/en/latest/notebooks/ModeSolver.html)

This allowed me to build a wrapper for their mode-solver engine which can be found on the [tidy3d branch of emepy](https://github.com/BYUCamachoLab/emepy/tree/tidy3d)

As for the sub pixel, that is useful to know they are using a sigmoid function for their smoothing technique, and I agree it makes sense we should see small differences in the fundamental mode as a result. 

> But for higher-order modes, I don't think sub-pixel smoothing is the main reason, because I found in testing that changes in the thickness of the boundary layer (the n_layer parameter) cause significant changes in the Neff for higher-order modes

Did you turn off the sub pixel smoothing for both EMEPy and Lumerical and compare for the higher order modes? I am confused by your statement here - it sounds like you are chaining the number of PML layers?

Thanks again, 
Ian
